### ISSUE TITLE
Nueva emisión de facturas

### ISSUE THREAD

**Issue by mdiago** [mdiago/wefinz#14]
1. Hay que incluir la posibilidad de asignar los impuestos soportados y retenidosa nivel de línea
2. Hay que incluir la posibilidad de facturas con sólo texto en las líneas (utilizando el campo texto de la linea de asiento con length 400 en lugar del ItemID e ItemName).

**Comment by bautista225** [comment]
Añadida la funcionalidad para insertar impuestos repercutidos a nivel de línea.

**Comment by bautista225** [comment]
Nueva emisión de facturas simple (simpledocumentissue) realizada.

Se ha añadido un campo denominado ItemText a cada uno de los objetos tipo ItemLine del módulo Business.Sales de la base de datos con tal de permitir descripciones de 400 caracteres (el campo ItemName que sólo permite 50 se dejaría a null).

Falta permitir la edición de dicho documento simple; así como los pasos por el flujo a nuevos documentos.

**Comment by bautista225** [comment]
Edición de documentos mediante la interfaz de emisión simple desarrollada y añadida a Wefinz.
