### ISSUE TITLE
Estudiar conveniencia de crear cuenta de gastos para cuota RETA

### ISSUE THREAD

**Issue by mdiago** [mdiago/wefinz#18]
Sería interesante poder diferenciar el importe que pagan a la seguridad social los autónomos por sus trabajadores, del importe que pagan por la cuota del RETA.
Hay que tener en cuenta que en el caso de autónomos societarios cuya cuota paga la propia empresa la forma de proceder debería ser, como figura en este [enlace](https://www.supercontable.com/informacion/Contabilidad/Asiento_de_cuota_de_autonomos_pagada_por_la_empresa..html), contabilizarlo a la cuenta de salarios (6400000000 | SUELDOS Y SALARIOS).

* Respecto a la consideración de esta situación como una retribución en especie, según figura en la referencia externa tengo mis reservas, ya que la remuneración es en metálico, se trata de un pago por cuenta del empleado.

**Comment by mdiago** [comment]
![image](https://user-images.githubusercontent.com/22330809/100226877-a1815a00-2f20-11eb-8900-f63a18cb0d2f.png)

**Comment by mserracosta** [comment]
Al modificar cuenta contable en el asiento, desaparece la línea en el Libro de Gastos. Si realizas búsqueda por interlocutor (TGSS) solo muestra las líneas que se han registrado en la cuenta contable 64200; desaparecen las que se han asociado a la cuenta 64205. Si se muestran los datos en extractos.

**Comment by mserracosta** [comment]
Tampoco aparece la línea de gasto en Impuestos\Resultados. Habría que verificar en que listados/modelos debe aparecer para incluirla.

**Comment by mdiago** [comment]
**Problema**

Al crear una nueva cuenta contable de gasto, ingreso o inversión está no aparece en la visualización del respectivo libro registro.

**Causas**

Los libros registro son una visualización particular del diario contable generada según unas opciones de configuración del módulo Accounting.Sme. Estas configuraciones se almacenan en los CIES (Community Information Entity):

- ExpensesBookSetting
- IncomeBookSetting
- AssetsBookSetting

Para los libros de ingresos, gastos e inversión respectivamente. En el caso concreto de los gastos, en la configuración encontramos el campo 'ExpensesAccountList' en el cual se incluye una lista de cuentas separadas por coma que se corresponden con las cuentas que se deben incluir en dicho libro.

**Solución**

Cuando se da alta una nueva cuenta contable de gasto, debe incluirse su valor en la lista de cuentas de gasto de la configuración.
Se ha solucionado el problema incluyendo la cuenta '6420500000 SEGURIDAD SOCIAL CUOTA RETA' en la lista de cuentas del libro de gastos.
