### ISSUE TITLE
Libros ingresos/gastos. Moneda extranjera

### ISSUE THREAD

**Issue by mserracosta** [mdiago/wefinz#20]
Cuando contabilizamos una factura en moneda extranjera el sistema permite registrar la conversión a EUR. Indicamos moneda de la factura (ej.USD) y el sistema convierte a EUR en otro campo distinto.

El asiento contable lo realiza en EUR; sin embargo en el Libro de Ingresos/gastos muestra la moneda extranjera, con lo que el sumatorio del Libro acumula importes de monedas diferentes.

Desconozco si esos acumulados se arrastran también a los modelos oficiales (Mod.130).

En mi opinión, los Libros deberían mostrar toda la información en EUR. No se que opinas vosotros.

**Comment by bautista225** [comment]
Cuando se implemente la obtención de los libros registro según las especificaciones de la AEAT, tendremos otro punto donde estará disponible la información de la forma que se desea.
