### ISSUE TITLE
Mayor. Orden lineas

### ISSUE THREAD

**Issue by mserracosta** [mdiago/wefinz#21]
**Problema 1:**
El mayor muestra la información ordenada por cuenta contable. Genial. Pero las líneas correspondientes a dicha cuenta contable deberían aparecer ordenadas por fecha de factura. De esta manera guardan un orden cronológico y resulta más fácil localizarlas y, en su caso, realizar un punteo.

Se echa de menos en todos los informes, Libros, etc la posibilidad de exportar a excel, imprimir listados en un formado legible y en algunos la posibilidad de elegir el rango de fechas del listado (filtro).

**Problema 2:**
Al seleccionar filtro en el Mayor por un periodo de tiempo el sistema muestra sólo las líneas comprendidas en dicho periodo. No obstante el sumatorio de cada cuenta contable acumula todas las facturas contabilizadas durante el año.

Entiendo que el sumatorio debería reflejar el acumulado de las facturas filtradas,

**Comment by bautista225** [comment]
Gracias por reportar los problemas Manuel!

Trabajos de rectificación concluidos.
