### ISSUE TITLE
Ventas. Crear documento. Sugerencias.

### ISSUE THREAD

**Issue by mserracosta** [mdiago/wefinz#22]
El sistema permite crear varias actividades económicas para cada empresa, y cuando creas un documento de venta permite seleccionar la actividad a la que se va a asignar la factura. No obstante el contador es único para ambas actividades.

Sugerencias:
1.- Crear contadores independientes para cada actividad económica. Imaginemos que una empresa (autónomo) tiene una actividad profesional (ingeniería) y además emite facturas por una actividad de alquiler de locales industriales. Entiendo que la facturación de cada una de esas actividades debe ser independiente. Además su tratamiento fiscal debe ser también independiente; en nuestro caso solo la actividad de ingeniería volcará sus datos para confeccionar los modelos 130 (Pago a cuenta IRPF) y 303, mientras que la actividad de alquiler no computa a efectos de IRPF (se considera rendimiento de capital mobiliario), pero si debemos tenerla en cuenta para las declaraciones de IVA (modelo 303).

2.- Crear series de facturación diferente (con contadores independientes) también resultaría útil sobre todo para empresas que quieren diferenciar sus distintas líneas de negocio. Yo, por ejemplo lo utilizo en mi actividad.

3.- En el desarrollo del nuevo panel de crear documentos (beta) sería interesante que se mostrara la serie y el número de la factura que estás creando.

4.- Datos adicionales. Permite la definición de tipos de IVA y retención por defecto, sin embargo va asociado a la propia factura de modo que no se repite en nuevas facturas el parámetro elegido. Entiendo que lo correcto sería asociar estos valores por defecto en cada actividad económica, de modo que se muestres por defecto al elegir la actividad en la creación de la factura.

Ejemplo. Imaginemos una actividad de enseñanza (exenta de IVA) desarrollada por la empresa X. Todas las facturas que va a emitir van a ser con base 0 o exentas. Si definimos que esa actividad es exenta de IVA el sistema pondrá por defecto tipo 0 de IVA y no será necesario cambiarlas una por una.

5.- Facturas periódicas. No acabo de entender como funcionan. Al activar la opción periódica en Datos Adicionales y no asociarle un email del destinatario me da un error al guardarla. Entiendo que se pretende que las facturas repetitivas se generen automáticamente, si bien, a mi entender, deberían llevar un control independiente. Se genera un "proyecto de factura periódica", en la que se indique la actividad y serie a la que se asocian, con los vencimientos predeterminados (periodicidad, fecha de inicio y fecha de fin), de modo que cuando salte la alerta se puedan generar automáticamente.

**Comment by bautista225** [comment]
Gracias por las sugerencias, las tenemos en cuenta para el módulo de "Facturación avanzada".

En cuanto al tipo de IVA a incluir por defecto, lo revisamos para la nueva interfaz de "Creación de documentos" en Ventas.
