### ISSUE TITLE
MENU. Propuesta reorganización menu aplicación

### ISSUE THREAD

**Issue by mserracosta** [mdiago/wefinz#23]
Adjunto propuesta 1 de reorganización de MENU. 
[MENU.pdf](https://github.com/mdiago/wefinz/files/5642486/MENU.pdf)

**Comment by bautista225** [comment]
Trabajos realizados. 
Hemos intentado refactorizar el panel aunando el estado actual de la aplicación y las sugerencias planteadas. 

Gracias por la propuesta Manuel!
