### ISSUE TITLE
Error al contabilizar factura recibida

### ISSUE THREAD

**Issue by mserracosta** [mdiago/wefinz#25]
Muestra el siguiente error:
"-4: Input.IndustryClassificationID not defined and Company.CompanyClassifications.length = 2"

Notas: he escaneado factura, al contabilizar detecto que se trata de un bien de inversión, por lo que cambio la cuenta de gasto por una cuenta de activo (2170); cambio manualmente cuenta de "IVA soportado para sustituir Iva soportado por compra bienes corrientes" por "IVA soportado por compra bienes de inversión".

No se si es posible correlacionar la cuenta de IVA soportado con la cuenta de gasto/activo, de modo que el sistema detecte que si indicas una cuenta de inmovilizado asigne automáticamente la cuenta de IVA soportado a bienes de inversión; en caso de asignar una cuenta de gasto mantendría la cuenta de IVA soportado bienes corrientes.

**Comment by mdiago** [comment]
Añadida mejora. Cuando al contabilizar una factura recibida, se cambia la línea de gasto por una cuenta del grupo 2, el programa propone el cambio de la cuenta de iva soportado y de la categoría de impuestos de IVA bienes corrientes a IVA inversión.
